In [2]:
import numpy as np
import pandas as pd
from pandas import Series, DataFrame

In [3]:
arr1 = np.arange(9).reshape(3,3)
arr1

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [4]:
np.concatenate([arr1,arr1], axis=1)

array([[0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5],
       [6, 7, 8, 6, 7, 8]])

In [5]:
np.concatenate([arr1,arr1], axis=0)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8],
       [0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [6]:
ser1 = Series([0,1,3], index=['T','U','V'])
ser2 = Series([3,4], index=['X','Y'])

In [7]:
ser1

T    0
U    1
V    3
dtype: int64

In [8]:
ser2

X    3
Y    4
dtype: int64

In [11]:
pd.concat([ser1,ser2])

T    0
U    1
V    3
X    3
Y    4
dtype: int64

In [13]:
# Creates DataFrame
pd.concat([ser1,ser2],axis=1)

0    1
T  0.0  NaN
U  1.0  NaN
V  3.0  NaN
X  NaN  3.0
Y  NaN  4.0

In [14]:
pd.concat([ser1,ser2], keys=['cat1','cat2'])

cat1  T    0
      U    1
      V    3
cat2  X    3
      Y    4
dtype: int64

In [15]:
dframe1 = DataFrame(np.random.randn(4,3), columns=['X','Y','Z'])
dframe2 = DataFrame(np.random.randn(3,3), columns=['Y','Q','X'])
dframe1

X         Y         Z
0  0.173896  0.135695  1.489170
1  0.965128 -0.218038  2.092607
2  2.857763  1.501233 -1.071577
3  1.176080 -0.211652  0.290455

In [16]:
dframe2

Y         Q         X
0  1.155779 -0.358420 -1.535705
1  0.132779  2.354205  0.203723
2  0.042305 -0.451678 -0.849673

In [18]:
pd.concat([dframe1,dframe2])

Q         X         Y         Z
0       NaN  0.173896  0.135695  1.489170
1       NaN  0.965128 -0.218038  2.092607
2       NaN  2.857763  1.501233 -1.071577
3       NaN  1.176080 -0.211652  0.290455
0 -0.358420 -1.535705  1.155779       NaN
1  2.354205  0.203723  0.132779       NaN
2 -0.451678 -0.849673  0.042305       NaN

In [19]:
# 
pd.concat([dframe1,dframe2],axis=1)

X         Y         Z         Y         Q         X
0  0.173896  0.135695  1.489170  1.155779 -0.358420 -1.535705
1  0.965128 -0.218038  2.092607  0.132779  2.354205  0.203723
2  2.857763  1.501233 -1.071577  0.042305 -0.451678 -0.849673
3  1.176080 -0.211652  0.290455       NaN       NaN       NaN

In [20]:
# we can also ignore the index
pd.concat([dframe1,dframe2], ignore_index=True)

Q         X         Y         Z
0       NaN  0.173896  0.135695  1.489170
1       NaN  0.965128 -0.218038  2.092607
2       NaN  2.857763  1.501233 -1.071577
3       NaN  1.176080 -0.211652  0.290455
4 -0.358420 -1.535705  1.155779       NaN
5  2.354205  0.203723  0.132779       NaN
6 -0.451678 -0.849673  0.042305       NaN