In [1]:
import numpy as np

In [3]:
arr = np.arange(5)
arr

array([0, 1, 2, 3, 4])

In [4]:
np.save('myFirstArraySave',arr)

In [5]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
np.load('myFirstArraySave.npy')

array([0, 1, 2, 3, 4])

In [7]:
arr1 = np.load('myFirstArraySave.npy')

In [8]:
arr2 = arr

In [9]:
arr1
arr2

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
arr1

array([0, 1, 2, 3, 4])

In [11]:
np.savez('myFirstZippedArrays.npz',x=arr1,y=arr2)

In [12]:
archive_array = np.load('myFirstZippedArrays.npz')

In [13]:
archive_array['x']

array([0, 1, 2, 3, 4])

In [14]:
archive_array['y']

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [15]:
arr = np.array([[1,2,3],[4,5,6]])
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [17]:
np.savetxt('myFirstTextArray.txt',arr,delimiter=',')

In [18]:
arr = np.loadtxt('myFirstTextArray.txt')

ValueError: could not convert string to float: b'1.000000000000000000e+00,2.000000000000000000e+00,3.000000000000000000e+00'