In [27]:
import numpy as np
import pandas as pd
from pandas import Series,DataFrame

In [2]:
arr = np.array(np.arange(20).reshape([4,5]))

In [3]:
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [4]:
arr[0]

array([0, 1, 2, 3, 4])

In [5]:
arr[1]

array([5, 6, 7, 8, 9])

In [6]:
arr[1][2] = 666

In [7]:
arr

array([[  0,   1,   2,   3,   4],
       [  5,   6, 666,   8,   9],
       [ 10,  11,  12,  13,  14],
       [ 15,  16,  17,  18,  19]])

In [8]:
arr

array([[  0,   1,   2,   3,   4],
       [  5,   6, 666,   8,   9],
       [ 10,  11,  12,  13,  14],
       [ 15,  16,  17,  18,  19]])

In [9]:
ser1 = Series(arr[1])

In [10]:
ser1

0      5
1      6
2    666
3      8
4      9
dtype: int64

In [11]:
ser1[2] = 777

In [12]:
ser1

0      5
1      6
2    777
3      8
4      9
dtype: int64

In [13]:
arr[1][2] = ser1

ValueError: setting an array element with a sequence.

In [16]:
arr1 = np.zeros([20,5],dtype=int)

In [17]:
arr1

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [18]:
l = [i for i in range(2)]

In [19]:
l

[0, 1]

In [20]:
g = ['this','that']

In [21]:
h = g*2

In [22]:
h

['this', 'that', 'this', 'that']

In [23]:
g = ['this','that']*3

In [25]:
len(2)

TypeError: object of type 'int' has no len()

In [30]:
data = DataFrame(np.zeros([22,12],dtype=int),
                     columns=[[i,i,i,i,i,i for i in range(2)],['Population','Susceptible','Immune','Recovered','Infected','Dead']*2])

SyntaxError: invalid syntax (<ipython-input-30-c0a09c541420>, line 2)

In [37]:
l = [join([i]*6 for i in range(2))]

NameError: name 'join' is not defined

In [35]:
l

[[[0, 0, 0, 0, 0, 0], [1, 1, 1, 1, 1, 1]]]

In [2]:
index1 = [i for i in range(2)]*6

In [3]:
index1

[0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1]

In [8]:
index2 = sorted([i for i in range(2)]*6)

In [9]:
index2

[0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1]

In [10]:
['Population','Susceptible','Immune','Recovered','Infected','Dead']*2

['Population',
 'Susceptible',
 'Immune',
 'Recovered',
 'Infected',
 'Dead',
 'Population',
 'Susceptible',
 'Immune',
 'Recovered',
 'Infected',
 'Dead']

In [12]:
len([2,2])

2

In [30]:
import numpy as np
import pandas as pd
from pandas import Series,DataFrame

locList = [0,1]
steps = 20
indexL = sorted([i for i in range(len(locList))]*6)
data = DataFrame(np.zeros([steps,6*len(locList)],dtype=int),
                     columns=[indexL,
                              ['Population','Susceptible','Immune','Recovered','Infected','Dead']*len(locList)])

In [31]:
data

0                                                     1  \
   Population Susceptible Immune Recovered Infected Dead Population   
0           0           0      0         0        0    0          0   
1           0           0      0         0        0    0          0   
2           0           0      0         0        0    0          0   
3           0           0      0         0        0    0          0   
4           0           0      0         0        0    0          0   
5           0           0      0         0        0    0          0   
6           0           0      0         0        0    0          0   
7           0           0      0         0        0    0          0   
8           0           0      0         0        0    0          0   
9           0           0      0         0        0    0          0   
10          0           0      0         0        0    0          0   
11          0           0      0         0        0    0          0   
12          0           0      0         0        0    0          0   
13          0           0      0         0        0    0          0   
14          0           0      0         0        0    0          0   
15          0           0      0         0        0    0          0   
16          0           0      0         0        0    0          0   
17          0           0      0         0        0    0          0   
18          0           0      0         0        0    0          0   
19          0           0      0         0        0    0          0   

                                               
   Susceptible Immune Recovered Infected Dead  
0            0      0         0        0    0  
1            0      0         0        0    0  
2            0      0         0        0    0  
3            0      0         0        0    0  
4            0      0         0        0    0  
5            0      0         0        0    0  
6            0      0         0        0    0  
7            0      0         0        0    0  
8            0      0         0        0    0  
9            0      0         0        0    0  
10           0      0         0        0    0  
11           0      0         0        0    0  
12           0      0         0        0    0  
13           0      0         0        0    0  
14           0      0         0        0    0  
15           0      0         0        0    0  
16           0      0         0        0    0  
17           0      0         0        0    0  
18           0      0         0        0    0  
19           0      0         0        0    0

In [33]:
dataNew = data.copy()

In [36]:
dataNew.head(7)

0                                                     1  \
  Population Susceptible Immune Recovered Infected Dead Population   
0          0           0      0         0        0    0          0   
1          0           0      0         0        0    0          0   
2          0           0      0         0        0    0          0   
3          0           0      0         0        0    0          0   
4          0           0      0         0        0    0          0   
5          0           0      0         0        0    0          0   
6          0           0      0         0        0    0          0   

                                              
  Susceptible Immune Recovered Infected Dead  
0           0      0         0        0    0  
1           0      0         0        0    0  
2           0      0         0        0    0  
3           0      0         0        0    0  
4           0      0         0        0    0  
5           0      0         0        0    0  
6           0      0         0        0    0

In [37]:
dataNew.loc[3,0].Population = 3

In [39]:
dataNew.head()

0                                                     1  \
  Population Susceptible Immune Recovered Infected Dead Population   
0          0           0      0         0        0    0          0   
1          0           0      0         0        0    0          0   
2          0           0      0         0        0    0          0   
3          3           0      0         0        0    0          0   
4          0           0      0         0        0    0          0   

                                              
  Susceptible Immune Recovered Infected Dead  
0           0      0         0        0    0  
1           0      0         0        0    0  
2           0      0         0        0    0  
3           0      0         0        0    0  
4           0      0         0        0    0

In [40]:
data.head()

0                                                     1  \
  Population Susceptible Immune Recovered Infected Dead Population   
0          0           0      0         0        0    0          0   
1          0           0      0         0        0    0          0   
2          0           0      0         0        0    0          0   
3          0           0      0         0        0    0          0   
4          0           0      0         0        0    0          0   

                                              
  Susceptible Immune Recovered Infected Dead  
0           0      0         0        0    0  
1           0      0         0        0    0  
2           0      0         0        0    0  
3           0      0         0        0    0  
4           0      0         0        0    0

In [41]:
'm'=='m'

True